### ISSUE TITLE
Where is 'Libraries.ttkScrollableNotebook' pulled from? (main.py line 15)

### ISSUE THREAD

**Issue by mfau** [Mips96/EzRO-gui#1]
Hello Mips,

This project looks cool and I'm trying to run it but I'm hitting some stumbling blocks.

I'm on a fresh python install and I've "pip installed" 'pygubu' but now I can't find where 'Libraries.ttkScrollableNotebook' (main.py line 15) is supposed to come from.

It would be nice to have a section in the README that lists which additional modules or library files the program needs to run.

Thanks,
Looking forward to trying your app.

**Comment by Mode8fx** [comment]
Have you tried downloading the latest release? It should have all the necessary libraries prepackaged.

**Comment by mfau** [comment]
That works! My derp, I was trying to run it from checked out source.
