### ISSUE TITLE
DAT Header Mismatch

### ISSUE THREAD

**Issue by wsamples01** [Mips96/EzRO-gui#2]
I get 2 issues when using this program. 

The first is when saving a configuration: 
"An error has occurred: Failed to save region settings. Reasons:"

When attempting to do an audit I get an error about "DAT header mismatch". Could someone explain the meaning of this error? Does the DAT or archive need to be named in a particular way?

**Comment by Mode8fx** [comment]
Thanks for bringing this up. Apparently there was an obvious syntax error that broke saving region settings. I don't know how I didn't catch it earlier, but I just pushed a new version 1.01 with a fix.

As for the second issue: The DAT file name only matters for automatic detection within the optional "Input No-Intro DAT Directory"; you can also supply a file manually on a per-system basis.

Aside from that, the DAT file should be Parent/Clone (see below), and the header name within the file needs to match the system name. Something like:
```
<datafile>
	<header>
		<name>Sega - Mega Drive - Genesis (Parent-Clone)</name>
		[other things go here]
	</header>
<datafile>
```
If and only if the <name> field starts with the correct system name (in this case, "Sega - Mega Drive - Genesis"), then it's considered a match. Parent-Clone DAT files obtained from No Intro's DAT-o-MATIC should work without needing to rename or modify them (as of v1.01), but let me know if there's a discrepancy.

**DAT-o-MATIC -> Download -> Daily -> P/C XML -> Prepare**
