### ISSUE TITLE
Copy Fail

### ISSUE THREAD

**Issue by LegendArmour** [Mips96/EzRO-gui#4]
Have an issue with copying,

Running Windows 11 

after audit on SNES using the NO-INTRO romset no matter which options selected it fails to copy roms to the output directory.
the region folders are created but the rooms themselves end with a fail to copy.
![Screenshot (16)](https://user-images.githubusercontent.com/35869955/192763327-98445d9c-18dd-4cc4-8fc2-35a1af3a8f61.png)

**Comment by LegendArmour** [comment]
Update on this seems to only happen due to the romset already being extracted - works fine when all rooms are compressed

solution - don't extract the romset before sorting

**Comment by Mode8fx** [comment]
That's odd, I just tried exporting unzipped SNES using those same settings and it worked fine. But at least you got it working _shrug_.
