### ISSUE TITLE
program crashes when there is more than one duplicate

### ISSUE THREAD

**Issue by L4R5** [Mips96/EzRO-gui#5]
Hi, I am using ezro to clean up roms and it cannot handle more than one duplicate. 

When auditing games, for each duplicate found it chooses the same name with a (1) in the name which then fails. It does not count up the duplicate numbers.

Version: 1.11

**Comment by Mode8fx** [comment]
Thanks for bringing this up. Duplicates were partially being handled, but having more than one duplicate non-zipped rom would crash due to an oversight on my part. I just uploaded a new version with a fix.
