### ISSUE TITLE
Ability to sort rom folders into letters?

### ISSUE THREAD

**Issue by lyden27** [Mips96/EzRO-gui#8]
On my Everdrive I cannot display all the game folders (containing each rom revision) unless they are sorted into small, more manageable directories. Would it be possible to add an option to move directories of each game into alphabetical folders or something similar? For example:

NES/A/Abadox/Abadox (USA).nes, Abadox (Japan).nes

Thank you for all the hard work by the way! This is by far my favorite rom organization software aside from a few minor issues!

**Comment by Mode8fx** [comment]
Added in v1.2. And glad you like it!
