### ISSUE TITLE
Mismatch DAT file

### ISSUE THREAD

**Issue by duemanisinistre** [Mips96/EzRO-gui#9]
I downloaded a No-Intro headered NES romset and a P/C XML headered DAT file from DAT-O-Matic but the audit says all the files in the system folder do not have a matching entry in the provided DAT file.
Then, I try with a headerLESS DAT file and the audit only a handful of roms do not have a matching entry.

At this point I calculate the md5 of a rom and look for it in the headered DAT file and it's in there. I look for it in the headerLESS DAT file and it's not, so the rom is HEADERED and it has a matching entry in the HEADERED DAT file but the audit fails.

Any idea what's happening?

**Comment by codefaux** [comment]
If you could provide which sources -- not links, sitenames / release names ie "the NES ROMs from no-intro 2023 from internetarchive" paired with xyz datecode of headered DAT from sitenamehere" -- there might be more movement on this. "I have a file combination that doesn't work" is very difficult to "nail down" from a development perspective, given how many thousands of variations there are.

**Comment by Mode8fx** [comment]
_Very_ late reply, but NES is a unique case since it has DATs for both headered and headerless. Most of the NES roms I've seen are verified according to the headerless DAT, so that's what should be used here. I just added that to the readme to prevent further confusion.

Closing this issue for now, but let me know if you have any further questions.

**Comment by TheRealBenForce** [comment]
@Mode8fx thanks, that was very helpful. Got stuck here with a few different tools.

**Comment by duemanisinistre** [comment]
> _Very_ late reply, but NES is a unique case since it has DATs for both headered and headerless. Most of the NES roms I've seen are verified according to the headerless DAT, so that's what should be used here. I just added that to the readme to prevent further confusion.
> 
> Closing this issue for now, but let me know if you have any further questions.

Emulators, with very few exceptions (Mesen is the only one I know), play only headered ROMs. It also doesn't make any sense to verify a headered set according to a headerless DAT, given Dat-O-Matic has both headered and headerless DATs.
